### ISSUE TITLE
Game exits cleanly (Ogre 1.12) instead of loading levels

### ISSUE THREAD

**Issue by etam** [stuntrally/stuntrally#38]
I'm trying to make openSUSE package usable again (https://build.opensuse.org/package/show/home:etamPL:branches:games/stuntrally). I've used version from master branch with patches submitted as #35, #36 and #37.

It compiles, it shows main menu, but when I choose to play a level, it just exits. Logs shows that it's a normal shutting down of game engine.

[stuntrally.log](https://github.com/stuntrally/stuntrally/files/7403344/stuntrally.log)

**Comment by scratchifoo** [comment]
Hello,

Are you sure it exits cleanly?  I just compiled in Gentoo, only using #35 , and it's also exiting during track loading.  I'm seeing segfault in dmesg; so in my case, it's not exiting cleanly, it crashes due to the segfault.

Also, is #35 addressing gcc only or glibc as well?  I tried compiling with gcc 9.3, and i get error from glibc during linking exec stage if I don't apply #35 : 

`[100%] Linking CXX executable ../stuntrally
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../lib64/libOgreMain.so: undefined reference to 'std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'`

I can compile with #35, but then I get the segfault...not sure if it's the root cause, just throwing this out there, wondering if you are getting it too and if this might be the cause...

**Comment by etam** [comment]
In my case there's no crash. As you can see in log I attached there is a whole sequence of shutting down and unloading components.

#35 is only about new gcc which defaults to new C++ standard and adds `std::optional` to scope. It has nothing to do with glibc. I suspect your linking problem comes from compiling different libs using different glibc versions.

If you get a segfault, try to get a backtrace with gdb. I might be helpful.

**Comment by scratchifoo** [comment]
You are right, everything was compiled with gcc11; I was trying to toggle different versions to compile stuntrally, didn't realize they all had to match.  After compiling everything with gcc10, I still got the segfault.  Since then, I switched and recompiled everything with gcc11 again.

I wanted to get some backtraces with gdb as you suggested, but ran into this issue when compiling with -DCMAKE_BUILD_TYPE=Debug

`/home/scratchi/Games/stuntrally/source/vdrift/isnan.h:8:27: error: ‘std::std’ has not been declared
    8 |         #define isnan(f)  std::isnan(f)
      |                           ^~~
`


I compiles fine if I use Release or RelWithDebInfo, but then I get the segfault, and the back traces don't really shed much light on what's happening beyond pointing to libOgreMain.so.1.9.0

`[107199.528147] stuntrally[30162]: segfault at 7ffeb14cadc0 ip 00007fab22a41bc0 sp 00007ffeb14cad20 error 6 in libOgreMain.so.1.9.0[7fab2279c000+2b5000]
[107199.528154] Code: 53 48 81 ec 28 04 00 00 48 8b bf a8 01 00 00 64 48 8b 04 25 28 00 00 00 48 89 84 24 18 04 00 00 31 c0 48 8d 9c 24 a0 00 00 00 <c7> 84 24 a0 00 00 00 00 00 00 00 48 8d 84 24 90 00 00 00 48 89 9c`

Do you have issues when compiling with Debug enabled?

**Comment by etam** [comment]
Make sure you're not hitting #29 

> Do you have issues when compiling with Debug enabled?

I didn't try. RelWithDebInfo usually works well enough for me.

**Comment by scratchifoo** [comment]
Hi,

When your game shuts down, is there anything interesting being logged in ogre.log or ogre.err?

So I've update to Ogre 1.12.9 and am getting similar behavior as your report where the game exits when trying to load the track.  I still get a segfault at the end, but it appears during the shutdown as it's shutting down ResourceManager.  This got me looking into ogre.log; wondering if you looked at it too and if it sheds light on this?

[ogre.log](https://github.com/stuntrally/stuntrally/files/7522692/ogre.log)
[ogre_err.log](https://github.com/stuntrally/stuntrally/files/7522705/ogre_err.log)

**Comment by etam** [comment]
I had no idea about those files. Here are mine:
[ogre.log](https://github.com/stuntrally/stuntrally/files/7523650/ogre.log)
[ogre_err.log](https://github.com/stuntrally/stuntrally/files/7523649/ogre_err.log)

**Comment by scratchifoo** [comment]
@paroj , any thoughts about this?

**Comment by paroj** [comment]
ogre must be compiled with `OGRE_RESOURCEMANAGER_STRICT=0` for stuntrally. See:
https://github.com/paroj/stuntrally/blob/8b0d2b053a486e407ba4ebadd4e9ab4f1ac50d5d/snapcraft.yaml#L34

**Comment by scratchifoo** [comment]
Thank you @paroj , that helps!  I can start a race and play Stuntrally on my Gentoo box now with Ogre 1.12.9

**Comment by cryham** [comment]
I think this is fixed right? If not reopen.
