### ISSUE TITLE
Release windows build with new changes

### ISSUE THREAD

**Issue by Tarek-Hasan** [stuntrally/stuntrally#51]
Please, release Windows build with new changes as it is not easy to build and use soft on Windows like Linux. But it's a lot easier now, contrary to what your old wiki suggests.
For your ease, I suggest you should use GitHub Actions to automate the building process. For reference; **Rigs of Rods**, open source vehicle simulator which is also built on Ogre game engine, uses GitHub Actions to automate their building process.
https://github.com/RigsOfRods/rigs-of-rods

**Comment by Calinou** [comment]
It's a good idea to move from Travis CI to GitHub Actions in general, as it provides a faster turnaround and has more features (including artifacts storage for 90 days).

**Comment by cryham** [comment]
Yes I want to do all this (changelog already has enough for release)
and this is already started in https://github.com/stuntrally/stuntrally/pull/39
I just have some issues using it on my Debian 11 setup.
I don't see the build working since it creashes using Ogre 1.13 which I didn't yet test and I'd rather go still with 1.9 which works well.
Any testing of that https://github.com/stuntrally/stuntrally/pull/39 pull request or hints would be great.

**Comment by Tarek-Hasan** [comment]
Hi @cryham, first I want to thank you for your awesome project.
I think you should build step by step (1.10 → 1.11 → 1.12 than 13) to the latest version to find out the build blockers and get rid of errors.
Documents to help with your transition from Ogre 1.9 to 13.
https://github.com/OGRECave/ogre/tree/master/Docs

Best of luck.

**Comment by AnotherFoxGuy** [comment]
You can now download a test build for windows here: https://nightly.link/stuntrally/stuntrally/workflows/build-game/master/stuntrally-win

**Comment by Tarek-Hasan** [comment]
Initial run looking good. Didn't encounter any bug yet. Will see after playing for some time.

**Comment by cryham** [comment]
Done. Stunt Rally 2.7 installer is now in [Releases](https://nightly.link/stuntrally/stuntrally/workflows/build-game/master/stuntrally-win).
